### ISSUE TITLE
formfield() does not include any server-side field validators for file size or MIME type

### ISSUE THREAD

**Issue by brianhwitte** [mbourqui/django-constrainedfilefield#24]
The model field validation works well, but there does not appear to be any server-side form field validation, beyond the default FileField validation.  If that is the intended behavior, the documentation should be updated to indicate that when "js_checker=False" no file size or MIME constraints will apply.

**Comment by mbourqui** [comment]
Hi @brianhwitte ,

Thanks for using django-constrainedfilefield!

Yes it does, this is the job of the `clean()` method:
https://github.com/mbourqui/django-constrainedfilefield/blob/3e1380feb3f1c46a0f320ea4ad5c08ade9576173/constrainedfilefield/fields/file.py#L59

It works according to the doc:
https://docs.djangoproject.com/en/3.0/ref/forms/validation/#

The js validation is only intended to improve user experience and reduce the load on the server to avoid processing invalid files. But in any case the validation will run prior to saving to the database.

Hope this helps!
