### ISSUE TITLE
Support for Django 4.x

### ISSUE THREAD

**Issue by hsenot** [mbourqui/django-constrainedfilefield#26]
Hi there,

In the process of upgrading our Django version to 4.0, we encountered the following incompatibility:
`cannot import name 'ugettext_lazy' from 'django.utils.translation'`

We were able to proceed by replacing the imports:
`from django.utils.translation import ugettext_lazy as _`
by
`from django.utils.translation import gettext_lazy as _`

in both fields/file.py and fields/image.py

Would you be able to apply these changes to enable other users to upgrade to Django 4?

Thanks in advance!

**Comment by mbourqui** [comment]
Hi @hsenot ,
Support for Django has been released :)

**Comment by hsenot** [comment]
Hooray :tada: - thanks Marc!
