### ISSUE TITLE
This package doesn't install from git repository due to missing ``Readme.rst`` 

### ISSUE THREAD

**Issue by jbzdak** [mbourqui/django-constrainedfilefield#9]
As you probably know ``pip`` supports installing packages from git repositories. Right now in my project I need to install this package in this way (as I need changes in https://github.com/mbourqui/django-constrainedfilefield/pull/8). 

This package doesn't install in such way due to missing ``Readme.rst``, which is generated on the fly from ``pypi_packager.sh``. 

I can think of following solutions to this issue: 

1. If ``Readme.rst`` is missing just ignore it and set empty ``long_description``; 
2. User ``Readme.md`` in such case; 
3. Store ``Readme.rst`` in repository (well technically this is having generated code in repository);

**Comment by mbourqui** [comment]
Hi,
Thanks for raising this issue, I rarely install packages from git repositories. I made changes based on your second suggestion, with a fallback on the first. Please check if this works for you, then I will publish a new release to pypi.

**Comment by jbzdak** [comment]
It works! Thanks, please release at your convenience!
